import { chromium } from 'playwright-core'
import { findChrome } from './lib.mjs'
const OUT='/tmp/claude-1000/-mnt-c-Current-LAB/3421315b-d71c-4208-af8b-ab4a756e9c8c/scratchpad'
const b = await chromium.launch({ executablePath: findChrome() })
const p = await (await b.newContext({ viewport:{width:1440,height:900} })).newPage()
const fails=[]; const ok=(c,m)=>{ console.log((c?'PASS':'FAIL')+' — '+m); if(!c) fails.push(m) }
p.on('pageerror',e=>fails.push('pageerror: '+e.message))
await p.goto('http://localhost:8968/'); await p.waitForTimeout(1600)
let t = await p.locator('body').innerText()
ok(!t.includes('800+') && !t.includes('Best-seller'), 'zéro faux avis, zéro faux best-seller')
ok(t.includes('La Signature'), 'Tamurt est LA Signature')
ok(t.includes("L'édition de l'été"), "l'édition saisonnière (Aman) remplace le café du mois périmé")
ok(t.includes('ne les inventera pas'), "la section « pas encore d'avis » dit la vérité")
ok(!t.includes('Kogia Business'), 'attribution corrigée (indépendant, Djerba)')
await p.screenshot({ path: OUT+'/coffee2_home.png' })
// fiche produit : Tamurt → tradition + composition + secret
await p.getByText('Tamurt', { exact: true }).first().click(); await p.waitForTimeout(700)
t = await p.locator('body').innerText()
ok(t.includes('La tradition —'), 'la fiche raconte LA TRADITION (plus de « bienfait » illégal)')
ok(t.includes('proportions restent le secret'), 'la Signature garde ses proportions secrètes')
ok(t.includes('orge (gluten)'), "l'allergène ORGE-GLUTEN est déclaré")
await p.screenshot({ path: OUT+'/coffee2_fiche.png' })
// ajouter + checkout COD
await p.getByRole('button', { name: /Ajouter au panier/ }).click(); await p.waitForTimeout(600)
await p.getByRole('button', { name: /Panier/ }).first().click(); await p.waitForTimeout(500)
await p.getByRole('button', { name: /Commander · paiement/ }).click(); await p.waitForTimeout(900)
const inputs = p.locator('input')
await inputs.nth(0).fill('Client Test')
await inputs.nth(1).fill('+216 20 123 456')
await p.locator('textarea, input').last()
await p.getByPlaceholder(/Rue, immeuble/).fill('12 rue des Jasmins, Houmt Souk')
t = await p.locator('body').innerText()
ok(t.includes('Paiement à la livraison') && !t.includes('e-mail') && !t.toLowerCase().includes('email'), 'checkout COD une page : ni e-mail ni compte')
await p.getByRole('button', { name: /Confirmer ·/ }).last().click(); await p.waitForTimeout(1000)
t = await p.locator('body').innerText()
ok(/CMD-\d+/.test(t), 'la commande sort avec sa référence')
await p.screenshot({ path: OUT+'/coffee2_confirm.png' })
// guides
await p.goto('http://localhost:8968/#/guides'); await p.waitForTimeout(800)
t = await p.locator('body').innerText()
ok(t.includes('zezoua') && t.includes('Conserver'), 'les 5 guides sont en ligne')
const ld = await p.evaluate(()=>[...document.querySelectorAll('script[type="application/ld+json"]')].map(s=>s.textContent).join(''))
ok(ld.includes('"@type":"Recipe"') || ld.includes('"@type": "Recipe"'), 'le schéma Recipe est posé (SEO)')
await p.screenshot({ path: OUT+'/coffee2_guides.png' })
await b.close()
console.log(fails.length ? `\n${fails.length} ÉCHEC(S)` : '\nTOUT PASSE')
process.exit(fails.length?1:0)
